version: '3.8'

services:
  flask_app:
    image: weather-app
    build:
      context: ./
      dockerfile: weather_app.dockerfile
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  
    depends_on:
      - flask_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    networks:
      - webnet

networks:
  webnet:

