version: '3.8'

services:
  weather-app:
    build:
      context: .
      dockerfile: weather_app.dockerfile 
    ports:
      - "5000:5000"  
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/app  
    restart: always  

